[tool.poetry]
name = "foxhustle-exploit"
version = "0.1.0"
description = ""
authors = ["PatriotRossii <patriotrossii2019@mail.ru>"]

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.27.1"
typer = "^0.4.1"
typing = "^3.10.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
